name: Black

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Formatting the code with Black
      run: |
        black $(git ls-files '*.py')
    - name: Add and commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "noreply@github.com"
        git add *
        git commit -m "Format \"$(git log -1 --pretty=%s)\" using Black"
