name: "GitHub Notion Issues Automation"

permissions:
    issues: read

# Run code on issue or issue comment
on: 
  issues:
    types: [opened, edited, milestoned]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Notion GitHub Issues Automation
        uses: Sajantoor/Notion-GitHub-Issues-Automation@1.0.0
        with:
            # Your current repository.
            repo: ${{ github.repository }} 
            # Your Notion API Key
            NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
            # Your Notion database ID
            NOTION_DATABASE: ${{ secrets.NOTION_DATABASE }}
            # The ID of the page that contains your database
            NOTION_PAGE_ID:  ${{ secrets.NOTION_PAGE_ID }}
