name: Sync issues to Notion

on:
  issues:
    types: [opened, edited, deleted, reopened, closed]
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: Edit-Mr/GitHub-issue-2-Notion@main
